---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: boshcpi/gce-cpi-release
inputs:
  - name: bosh-cpi-src
  - name: ci
  - name: infrastructure
  - name: stemcell
run:
  path: ci/ci/tasks/run-int.sh
params:
  google_json_key_data: replace-me
