---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: boshcpi/gce-cpi-release
    tag: v1
inputs:
  - name: bosh-cpi-src
  - name: stemcell
  - name: bats
run:
  path: bosh-cpi-src/ci/tasks/run-bats.sh
params:
  google_project:                   replace-me
  google_region:                    replace-me
  google_zone:                      replace-me
  google_json_key_data:             replace-me
  google_network:                   replace-me
  google_subnetwork:                replace-me
  google_subnetwork_range:          replace-me
  google_subnetwork_gw:             replace-me
  google_firewall_internal:         replace-me
  google_firewall_external:         replace-me
  google_address_director:          replace-me
  google_address_bats:              replace-me
  google_address_static_bats:       replace-me
  google_address_static_bats_range: replace-me
  google_address_static_bats_dir:   replace-me
  base_os:                          replace-me
  stemcell_name:                    replace-me
  bat_vcap_password:                replace-me
