---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: boshcpi/gce-cpi-release
    tag: v1
inputs:
  - name: bosh-cpi-src
  - name: bosh-cpi-release
  - name: bosh-release
  - name: stemcell
  - name: bosh-init
outputs:
  - name: deployment
run:
  path: bosh-cpi-src/ci/tasks/setup-director.sh
params:
  BOSH_INIT_LOG_LEVEL:      warn
  google_project:           replace-me
  google_region:            replace-me
  google_zone:              replace-me
  google_json_key_data:     replace-me
  google_network:           replace-me
  google_subnetwork:           replace-me
  google_firewall_internal: replace-me
  google_firewall_external: replace-me
  google_address_director:  replace-me
  private_key_user:         replace-me
  private_key_data:         replace-me
  director_username:        replace-me
  director_password:        replace-me
