---
groups:
  - name: bosh-google-stemcell
    jobs:
      - ubuntu-trusty-stemcell
      - centos-7-stemcell

  - name: ubuntu
    jobs:
      - ubuntu-trusty-stemcell

  - name: centos
    jobs:
      - centos-7-stemcell

jobs:
  - name: ubuntu-trusty-stemcell
    plan:
      - aggregate:
        - {trigger: true, get: stemcell, resource: ubuntu-stemcells}
        - {trigger: false, get: bosh-cpi-src}

      - task: create-light-stemcell
        file: bosh-cpi-src/ci/stemcell/tasks/build-light-stemcell.yml
        privileged: true
        params:
          BUCKET_NAME:     {{google_stemcells_bucket_name}}

      - aggregate:
        - put: bosh-ubuntu-raw-stemcells
          params:
            file: raw-stemcell/bosh-stemcell-*-google-kvm-ubuntu-trusty-go_agent-raw.tar.gz
            predefined_acl: "publicRead"

        - put: bosh-ubuntu-light-stemcells
          params:
            file: light-stemcell/light-bosh-stemcell-*-google-kvm-ubuntu-trusty-go_agent.tgz
            predefined_acl: "publicRead"

        - put: bosh-ubuntu-raw-stemcells-sha1
          params:
            file: raw-stemcell/bosh-stemcell-*-google-kvm-ubuntu-trusty-go_agent-raw.tar.gz.sha1
            predefined_acl: "publicRead"

        - put: bosh-ubuntu-light-stemcells-sha1
          params:
            file: light-stemcell/light-bosh-stemcell-*-google-kvm-ubuntu-trusty-go_agent.tgz.sha1
            predefined_acl: "publicRead"

  - name: centos-7-stemcell
    plan:
      - aggregate:
        - {trigger: true, get: stemcell, resource: centos-stemcells}
        - {trigger: false, get: bosh-cpi-src}

      - task: create-light-stemcell
        file: bosh-cpi-src/ci/stemcell/tasks/build-light-stemcell.yml
        privileged: true
        params:
          BUCKET_NAME:     {{google_stemcells_bucket_name}}

      - aggregate:
        - put: bosh-centos-raw-stemcells
          params:
            file: raw-stemcell/bosh-stemcell-*-google-kvm-centos-7-go_agent-raw.tar.gz
            predefined_acl: "publicRead"

        - put: bosh-centos-light-stemcells
          params:
            file: light-stemcell/light-bosh-stemcell-*-google-kvm-centos-7-go_agent.tgz
            predefined_acl: "publicRead"

        - put: bosh-centos-raw-stemcells-sha1
          params:
            file: raw-stemcell/bosh-stemcell-*-google-kvm-centos-7-go_agent-raw.tar.gz.sha1
            predefined_acl: "publicRead"

        - put: bosh-centos-light-stemcells-sha1
          params:
            file: light-stemcell/light-bosh-stemcell-*-google-kvm-centos-7-go_agent.tgz.sha1
            predefined_acl: "publicRead"

resources:
  - name: bosh-cpi-src
    type: git
    source:
      uri: https://github.com/cloudfoundry-incubator/bosh-google-cpi-release.git
      branch: master

  - name: centos-stemcells
    type: s3
    source:
      regexp: {{bosh_stemcell_centos_regexp}}
      bucket: {{bosh_stemcell_bucket}}

  - name: ubuntu-stemcells
    type: s3
    source:
      regexp: {{bosh_stemcell_ubuntu_regexp}}
      bucket: {{bosh_stemcell_bucket}}

  - name: bosh-ubuntu-raw-stemcells
    type: gcs-resource
    source:
      json_key: {{google_json_key_data}}
      bucket:   {{google_stemcells_bucket_name}}
      regexp:   bosh-stemcell-([0-9\.]+)-google-kvm-ubuntu-trusty-go_agent-raw.tar.gz

  - name: bosh-ubuntu-raw-stemcells-sha1
    type: gcs-resource
    source:
      json_key: {{google_json_key_data}}
      bucket:   {{google_stemcells_bucket_name}}
      regexp:   bosh-stemcell-([0-9\.]+)-google-kvm-ubuntu-trusty-go_agent-raw.tar.gz.sha1

  - name: bosh-ubuntu-light-stemcells
    type: gcs-resource
    source:
      json_key: {{google_json_key_data}}
      bucket:   {{google_stemcells_bucket_name}}
      regexp:   light-bosh-stemcell-([0-9\.]+)-google-kvm-ubuntu-trusty-go_agent.tgz

  - name: bosh-ubuntu-light-stemcells-sha1
    type: gcs-resource
    source:
      json_key: {{google_json_key_data}}
      bucket:   {{google_stemcells_bucket_name}}
      regexp:   light-bosh-stemcell-([0-9\.]+)-google-kvm-ubuntu-trusty-go_agent.tgz.sha1

  - name: bosh-centos-raw-stemcells
    type: gcs-resource
    source:
      json_key: {{google_json_key_data}}
      bucket:   {{google_stemcells_bucket_name}}
      regexp:   bosh-stemcell-([0-9\.]+)-google-kvm-centos-7-go_agent-raw.tar.gz

  - name: bosh-centos-raw-stemcells-sha1
    type: gcs-resource
    source:
      json_key: {{google_json_key_data}}
      bucket:   {{google_stemcells_bucket_name}}
      regexp:   bosh-stemcell-([0-9\.]+)-google-kvm-centos-7-go_agent-raw.tar.gz.sha1

  - name: bosh-centos-light-stemcells
    type: gcs-resource
    source:
      json_key: {{google_json_key_data}}
      bucket:   {{google_stemcells_bucket_name}}
      regexp:   light-bosh-stemcell-([0-9\.]+)-google-kvm-centos-7-go_agent.tgz

  - name: bosh-centos-light-stemcells-sha1
    type: gcs-resource
    source:
      json_key: {{google_json_key_data}}
      bucket:   {{google_stemcells_bucket_name}}
      regexp:   light-bosh-stemcell-([0-9\.]+)-google-kvm-centos-7-go_agent.tgz.sha1

resource_types:
  - name: gcs-resource
    type: docker-image
    source:
      repository: frodenas/gcs-resource
