---
groups:
  - name: bosh-google-cpi-release
    jobs:
      - test-unit
      - build-candidate
      - setup-infrastructure
      - deploy-ubuntu
      - run-bats
      - run-int
      - teardown-infrastructure
      - promote-candidate

jobs:
  - name: test-unit
    plan:
      - aggregate:
        - {trigger: true, get: bosh-cpi-src, resource: bosh-cpi-src-in}

      - task: unit-tests
        file: bosh-cpi-src/ci/tasks/unit-tests.yml

  - name: build-candidate
    serial: true
    plan:
      - aggregate:
        - {trigger: true, passed: [test-unit], get: bosh-cpi-src,   resource: bosh-cpi-src-in}
        - {trigger: false,                     get: version-semver, params: {bump: patch}}

      - put: version-semver
        params: {file: version-semver/number}

      - task: build-release
        file: bosh-cpi-src/ci/tasks/build-candidate.yml

      - put: bosh-cpi-dev-artifacts
        params: {file: candidate/*.tgz}

      - put: bosh-cpi-dev-artifacts-sha1
        params: {file: candidate/*.tgz.sha1}

  - name: setup-infrastructure
    serial_groups: [run-bats, run-int]
    plan:
      - aggregate:
        - {trigger: true, passed: [build-candidate], get: bosh-cpi-src, resource: bosh-cpi-src-in}
        - {trigger: true,                            get: stemcell, resource: google-ubuntu-stemcell}

      - task: teardown-infrastructure
        file: bosh-cpi-src/ci/tasks/teardown-infrastructure.yml
        config:
          params:
            google_project:                 {{google_project}}
            google_region:                  {{google_region}}
            google_zone:                    {{google_zone}}
            google_json_key_data:           {{google_json_key_data}}
            google_auto_network:            {{google_auto_network}}
            google_network:                 {{google_network}}
            google_subnetwork:              {{google_subnetwork}}
            google_firewall_internal:       {{google_firewall_internal}}
            google_firewall_external:       {{google_firewall_external}}
            google_backend_service:         {{google_backend_service}}
            google_target_pool:             {{google_target_pool}}
            google_address_director_ubuntu: {{google_address_director_ubuntu}}
            google_address_bats_ubuntu:     {{google_address_bats_ubuntu}}
            google_address_int_ubuntu:      {{google_address_int_ubuntu}}

      - task: setup-infrastructure
        file: bosh-cpi-src/ci/tasks/setup-infrastructure.yml
        config:
          params:
            google_project:                 {{google_project}}
            google_region:                  {{google_region}}
            google_zone:                    {{google_zone}}
            google_json_key_data:           {{google_json_key_data}}
            google_auto_network:            {{google_auto_network}}
            google_network:                 {{google_network}}
            google_subnetwork:              {{google_subnetwork}}
            google_subnetwork_range:        {{google_subnetwork_range}}
            google_firewall_internal:       {{google_firewall_internal}}
            google_firewall_external:       {{google_firewall_external}}
            google_backend_service:         {{google_backend_service}}
            google_target_pool:             {{google_target_pool}}
            google_address_director_ubuntu: {{google_address_director_ubuntu}}
            google_address_bats_ubuntu:     {{google_address_bats_ubuntu}}
            google_address_int_ubuntu:      {{google_address_int_ubuntu}}

  - name: teardown-infrastructure
    serial_groups: [run-bats, run-int]
    plan:
      - aggregate:
        - {trigger: true, passed: [run-bats, run-int], get: bosh-cpi-src, resource: bosh-cpi-src-in}

      - task: teardown-infrastructure
        file: bosh-cpi-src/ci/tasks/teardown-infrastructure.yml
        config:
          params:
            google_project:                 {{google_project}}
            google_region:                  {{google_region}}
            google_zone:                    {{google_zone}}
            google_json_key_data:           {{google_json_key_data}}
            google_auto_network:            {{google_auto_network}}
            google_network:                 {{google_network}}
            google_subnetwork:              {{google_subnetwork}}
            google_firewall_internal:       {{google_firewall_internal}}
            google_firewall_external:       {{google_firewall_external}}
            google_backend_service:         {{google_backend_service}}
            google_target_pool:             {{google_target_pool}}
            google_address_director_ubuntu: {{google_address_director_ubuntu}}
            google_address_bats_ubuntu:     {{google_address_bats_ubuntu}}
            google_address_int_ubuntu:      {{google_address_int_ubuntu}}

  - name: deploy-ubuntu
    serial_groups: [run-bats, run-int]
    plan:
      - aggregate:
        - {trigger: true, passed: [build-candidate, setup-infrastructure],  get: bosh-cpi-src, resource: bosh-cpi-src-in}
        - {trigger: true,  passed: [build-candidate],                       get: bosh-cpi-release, resource: bosh-cpi-dev-artifacts}
        - {trigger: true, passed: [setup-infrastructure],                   get: stemcell, resource: google-ubuntu-stemcell}
        - {trigger: false,                                                  get: bosh-init}
        - {trigger: false,                                                  get: bosh-release}
        - {trigger: false,                                                  get: dummy-boshrelease}

      - task: setup-director
        file: bosh-cpi-src/ci/tasks/setup-director.yml
        config:
          params:
            google_project:                 {{google_project}}
            google_region:                  {{google_region}}
            google_zone:                    {{google_zone}}
            google_json_key_data:           {{google_json_key_data}}
            google_network:                 {{google_network}}
            google_subnetwork:              {{google_subnetwork}}
            google_subnetwork_range:        {{google_subnetwork_range}}
            google_subnetwork_gw:           {{google_subnetwork_gw}}
            google_firewall_internal:       {{google_firewall_internal}}
            google_firewall_external:       {{google_firewall_external}}
            google_address_director:        {{google_address_director_ubuntu}}
            google_address_static_director: {{google_address_static_director_ubuntu}}
            private_key_user:               {{private_key_user}}
            private_key_data:               {{private_key_data}}
            director_username:              {{director_username}}
            director_password:              {{director_password}}
        on_failure:
          task: teardown-director
          file: bosh-cpi-src/ci/tasks/teardown-director.yml

      - task: deploy-dummy
        file: bosh-cpi-src/ci/tasks/deploy-dummy.yml
        config:
          params:
            google_project:           {{google_project}}
            google_region:            {{google_region}}
            google_zone:              {{google_zone}}
            google_json_key_data:     {{google_json_key_data}}
            google_network:           {{google_network}}
            google_subnetwork:        {{google_subnetwork}}
            google_subnetwork_range:  {{google_subnetwork_range}}
            google_subnetwork_gw:     {{google_subnetwork_gw}}
            google_firewall_internal: {{google_firewall_internal}}
            google_address_director:  {{google_address_director_ubuntu}}
            base_os:                  Ubuntu
            stemcell_name:            bosh-google-kvm-ubuntu-trusty-go_agent
            director_username:        {{director_username}}
            director_password:        {{director_password}}
        on_failure:
          task: teardown-director
          file: bosh-cpi-src/ci/tasks/teardown-director.yml

  - name: run-bats
    serial: true
    serial_groups: [run-bats]
    plan:
      - aggregate:
        - {trigger: true, passed: [build-candidate, deploy-ubuntu], get: bosh-cpi-src, resource: bosh-cpi-src-in}
        - {trigger: true, passed: [deploy-ubuntu],                  get: stemcell, resource: google-ubuntu-stemcell}
        - {trigger: false, passed: [deploy-ubuntu],    get: bosh-cpi-release,       resource: bosh-cpi-dev-artifacts}

        - {trigger: false,                                          get: bats}

      - task: run-bats
        file: bosh-cpi-src/ci/tasks/run-bats.yml
        config:
          params:
            google_project:                             {{google_project}}
            google_region:                              {{google_region}}
            google_zone:                                {{google_zone}}
            google_json_key_data:                       {{google_json_key_data}}
            google_network:                             {{google_network}}
            google_subnetwork:                          {{google_subnetwork}}
            google_subnetwork_range:                    {{google_subnetwork_range}}
            google_subnetwork_gw:                       {{google_subnetwork_gw}}
            google_firewall_internal:                   {{google_firewall_internal}}
            google_firewall_external:                   {{google_firewall_external}}
            google_address_director:                    {{google_address_director_ubuntu}}
            google_address_bats:                        {{google_address_bats_ubuntu}}
            google_address_static_bats:                 {{google_address_static_bats_ubuntu}}
            google_address_static_available_range_bats: {{google_address_static_bats_available_range_ubuntu}}
            google_address_static_pair_bats:            {{google_address_static_pair_bats_ubuntu}}
            base_os:                                    Ubuntu
            stemcell_name:                              bosh-google-kvm-ubuntu-trusty-go_agent
            bat_vcap_password:                          {{bat_vcap_password}}
            private_key_data:                           {{private_key_data}}

  - name: run-int
    serial_groups: [run-int]
    plan:
      - aggregate:
        - {trigger: true, passed: [build-candidate, deploy-ubuntu], get: bosh-cpi-src, resource: bosh-cpi-src-in}
        - {trigger: true, passed: [deploy-ubuntu],                  get: stemcell, resource: google-ubuntu-stemcell}
        - {trigger: false, passed: [deploy-ubuntu],    get: bosh-cpi-release,       resource: bosh-cpi-dev-artifacts}


      - task: run-int
        file: bosh-cpi-src/ci/tasks/run-int.yml
        config:
          params:
            google_project:                   {{google_project}}
            google_region:                    {{google_region}}
            google_zone:                      {{google_zone}}
            google_json_key_data:             {{google_json_key_data}}
            google_auto_network:              {{google_auto_network}}
            google_network:                   {{google_network}}
            google_subnetwork:                {{google_subnetwork}}
            google_firewall_internal:         {{google_firewall_internal}}
            google_firewall_external:         {{google_firewall_external}}
            google_address_int:               {{google_address_int_ubuntu}}
            google_address_static_int:        {{google_address_static_int_ubuntu}}
            google_target_pool:               {{google_target_pool}}
            google_backend_service:           {{google_backend_service}}


  - name: promote-candidate
    serial: true
    plan:
      - aggregate:
        - {trigger: false, passed: [run-int,run-bats], get: bosh-cpi-src,           resource: bosh-cpi-src-in}
        - {trigger: false, passed: [run-int,run-bats], get: stemcell,               resource: google-ubuntu-stemcell}
        - {trigger: false, passed: [run-int,run-bats], get: bosh-cpi-release,       resource: bosh-cpi-dev-artifacts}
        - {trigger: true,  passed: [run-int,run-bats], get: stemcell,               resource: google-ubuntu-stemcell}
        - {trigger: false,                             get: release-version-semver, params: {bump: major}}
      
      - task: promote
        file: bosh-cpi-src/ci/tasks/promote-candidate.yml
        config:
          params:
            release_blobs_access_key: {{release_blobs_access_key}}
            release_blobs_secret_key: {{release_blobs_secret_key}}

      - put: bosh-cpi-src-out
        params: {repository: promoted/repo, rebase: true, tag_prefix: "v", tag: promoted/integer_version}

      - put: bosh-cpi-artifacts
        params:
          file: promoted/*.tgz
          predefined_acl: "publicRead"
      
      - put: bosh-cpi-artifacts-sha1
        params:
          file: promoted/*.tgz.sha1
          predefined_acl: "publicRead"


resources:
  - name: bosh-cpi-src-in
    type: git
    source:
      uri: https://github.com/cloudfoundry-incubator/bosh-google-cpi-release.git
      branch: master
      ignore_paths:
        - .final_builds/**/*.yml
        - releases/**/*.yml

  - name: bosh-cpi-src-out
    type: git
    source:
      uri: git@github.com:cloudfoundry-incubator/bosh-google-cpi-release.git
      branch: master
      private_key: {{github_deployment_key_bosh_google_cpi_release}}

  - name: bosh-cpi-dev-artifacts
    type: gcs-resource
    source:
      json_key: {{google_json_key_data}}
      bucket:   {{google_releases_bucket_name}}
      regexp:   bosh-google-cpi-([0-9]+\.[0-9]+\.[0-9]+)\.tgz

  - name: bosh-cpi-dev-artifacts-sha1
    type: gcs-resource
    source:
      json_key: {{google_json_key_data}}
      bucket:   {{google_releases_bucket_name}}
      regexp:   bosh-google-cpi-([0-9]+\.[0-9]+\.[0-9]+)\.tgz.sha1

  - name: bosh-cpi-artifacts
    type: gcs-resource
    source:
      json_key: {{google_json_key_data}}
      bucket:   {{google_releases_bucket_name}}
      regexp:   bosh-google-cpi-([0-9]+)\.tgz

  - name: bosh-cpi-artifacts-sha1
    type: gcs-resource
    source:
      json_key: {{google_json_key_data}}
      bucket:   {{google_releases_bucket_name}}
      regexp:   bosh-google-cpi-([0-9]+)\.tgz\.sha1

  - name: version-semver
    type: semver
    source:
      key:               current-version
      bucket:            {{version_semver_bucket_name}}
      access_key_id:     {{version_semver_access_key}}
      secret_access_key: {{version_semver_secret_key}}
      region:            {{version_semver_region}}
      endpoint:          storage.googleapis.com

  - name: release-version-semver
    type: semver
    source:
      key:               release-version
      bucket:            {{version_semver_bucket_name}}
      access_key_id:     {{version_semver_access_key}}
      secret_access_key: {{version_semver_secret_key}}
      region:            {{version_semver_region}}
      endpoint:          storage.googleapis.com

  - name: bosh-init
    type: s3
    source:
      regexp: bosh-init-([0-9.]+)-linux-amd64
      bucket: bosh-init-artifacts
      region_name: us-east-1

  - name: bosh-release
    type: bosh-io-release
    source:
      repository: cloudfoundry/bosh

  - name: bats
    type: git
    source:
      uri: https://github.com/cloudfoundry/bosh-acceptance-tests.git
      branch: master

  - name: dummy-boshrelease
    type: git
    source:
      uri: https://github.com/pivotal-cf-experimental/dummy-boshrelease.git
      branch: master

  - name: google-ubuntu-stemcell
    type: gcs-resource
    source:
      json_key: {{google_json_key_data}}
      bucket:   {{google_stemcells_bucket_name}}
      regexp:   light-bosh-stemcell-([0-9\.]+)-google-kvm-ubuntu-trusty-go_agent.tgz
resource_types:
  - name: gcs-resource
    type: docker-image
    source:
      repository: frodenas/gcs-resource
